name: paginatorx
description: paginatorx is a Flutter package that helps you to paginate data from the network or from any other source.
version: 1.0.1
homepage: https://github.com/unix14/paginatorx

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
